# Generated by Django 3.0.11 on 2020-12-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('D', 'DEFAULT'), ('K', 'KAKAO')], default='D', max_length=1),
        ),
    ]
